getlantern/lantern-client

- .github/workflows/build-darwin.yml
- .github/workflows/release.yml
- Makefile
Resolves https://github.com/getlantern/engineering/issues/1236
> Build universal macOS Binary

- .github/workflows/build-darwin.yml
- .github/workflows/build-windows.yml
- .github/workflows/release.yml
- installer-resources-lantern/windows/lantern.nsi
- lib/common/ui/app_webview.dart
- lib/plans/checkout.dart
- lib/vpn/vpn_switch.dart
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This updates the desktop app to use https://github.com/wgh136/flutter_windows_webview instead of https://pub.dev/packages/flutter_inappwebview for the webview on Windows (flutter_inappwebview doesn't support Windows yet -- there's an initial implementation in the works though).
> Use flutter_windows_webview on Windows

- assets/locales/en.po
- desktop/lib.go
- lib/account/report_issue.dart
- lib/app.dart
- lib/common/session_model.dart
- lib/common/ui/app_loading_dialog.dart
- lib/ffi.dart
- lib/plans/checkout.dart
- lib/plans/reseller_checkout.dart
- pubspec.yaml
- Added error handling for multiple methods
- Fixed issue with report Issue
- Use compute to avoid UI Freeze
- Fixed issue Device not showing up.
> Desktop Error handling and other hot fix

- ios/Podfile.lock
- macos/Podfile.lock
- pubspec.lock
When I try to launch the desktop app with the latest on main, I am getting the following error:
```
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             518ms
CocoaPods' output:
↳
Preparing
Analyzing dependencies
Inspecting targets to integrate
Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)
...
[!] CocoaPods could not find compatible versions for pod "Sentry/HybridSDK":
In snapshot (Podfile.lock):
Sentry/HybridSDK (= 8.20.0)
In Podfile:
sentry_flutter (from `Flutter/ephemeral/.symlinks/plugins/sentry_flutter/macos`) was resolved to 0.0.1, which depends on
Sentry/HybridSDK (= 8.21.0)
You have either:
* out-of-date source …
```
> Run pod repo update

- desktop/app/app.go
- desktop/app/pro.go
- desktop/app/sysproxy.go
- desktop/lib.go
- desktop/ws/service.go
- lib/common/session_model.dart
- lib/ffi.dart
- lib/plans/checkout.dart
- lib/plans/plan_details.dart
- lib/plans/reseller_checkout.dart
When switching languages, it's no longer necessary to switch tabs and the changes show up immediately
> Handle language changes over websocket channel

- android/app/src/main/kotlin/org/getlantern/lantern/model/PaymentMethod.kt
- android/app/src/main/kotlin/org/getlantern/lantern/model/ProviderInfo.kt
Fix crash when forcing country to Russia
> Add PaymentWall to PaymentProvider enum

- android/app/build.gradle
- android/app/src/main/kotlin/io/lantern/model/dbadapter/DBAdapter.kt
- android/build.gradle
Depends on-:https://github.com/getlantern/db-android/pull/15
Depends on-:https://github.com/getlantern/messaging-android/pull/51
> Upgrade Android-db.

- android/app/src/main/kotlin/io/lantern/model/SessionModel.kt
- desktop/app/app.go
- desktop/lib.go
- internalsdk/session_model.go
- lib/app.dart
- lib/common/common_desktop.dart
- lib/common/session_model.dart
- lib/custom_bottom_bar.dart
- lib/custom_bottom_item.dart
- lib/ffi.dart
- lib/home.dart
- lib/plans/payment_provider.dart
- lib/vpn/try_lantern_chat.dart
- Fixed issue with system tray.
- Make the VPN tab as default and remove saving implementation.
- Added flashlight version as SDK version in the setting.
- Small other changes.
> Desktop Fixes

- lib/common/session_model.dart
Fixes the following crash on desktop after merging https://github.com/getlantern/lantern-client/pull/1062
```
flutter: [2024-05-01 16:09:47.022011 | Catcher 2 | INFO] ============================== CATCHER 2 LOG ==============================
flutter: [2024-05-01 16:09:47.022106 | Catcher 2 | INFO] Crash occurred on 2024-05-01 16:09:47.020733
flutter: [2024-05-01 16:09:47.022166 | Catcher 2 | INFO]
flutter: [2024-05-01 16:09:47.022289 | Catcher 2 | INFO] ------- DEVICE INFO -------
flutter: [2024-05-01 16:09:47.022443 | Catcher 2 | INFO] computerName: atavism's MacBook Air
flutter: [2024-05-01 16:09:47.022475 | Catcher 2 | INFO] hostName: Darwin
flutter: [2024-05-01 16:09:47.022529 | Catcher 2 | INFO] arch: arm64
flutter: [2024-05-01 16:09:47.022616 | Catcher 2 | INFO] model: Mac14,15 …
```
> Only call enableScreenshot on Android

- assets/locales/en.po
- desktop/app/app.go
- desktop/lib.go
- lib/account/report_issue.dart
- lib/account/settings.dart
- lib/common/session_model.dart
- lib/common/ui/custom/text_field.dart
- lib/ffi.dart
Resolves https://github.com/getlantern/engineering/issues/1361
> Fix issues with report an issue page

- android/build.gradle
- android/settings.gradle
- pubspec.lock
- pubspec.yaml
Looks like there is some issue on `androidx.appcompat:appcompat:1.6.1` on the latest flutter version I am getting error for the time being I downgraded the flutter version and upgraded the Gradle version to the stable.
```
ava.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
at androidx.activity.OnBackPressedDispatcher$Api33Impl.createOnBackInvokedCallback(OnBackPressedDispatcher.java:344)
at androidx.activity.OnBackPressedDispatcher.<init>(OnBackPressedDispatcher.java:130)
at androidx.activity.ComponentActivity.<init>(ComponentActivity.java:152)
at androidx.fragment.app.FragmentActivity.<init>(FragmentActivity.java:108)
at androidx.appcompat.app.AppCompatActivity.<init>(AppCompatActivity.java:96)
at …
```
> Upgrade version to stable and downgrade flutter version.

- .github/workflows/build-darwin.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/release.yml
- pubspec.yaml
And explicitly set the version to 3.19.6 in pubspec.yaml (it's necessary to have an exact Flutter version defined for flutter-version-file to work)
> Update CI to install version of Flutter from pubspec.yaml 

- go.mod
- go.sum
- lib/plans/plan_details.dart
- lib/plans/play_checkout.dart
- Fixed Multiple routes issue
- Updated flashlight
> Android 7.8.6 Hotfixes

- lib/account/follow_us.dart
Potentially closes https://github.com/getlantern/engineering/issues/1444.
> Fix social media links

- .github/release.yml
thanks @thomasjib for catching this
> include all PRs in changelog

- android/app/build.gradle
- android/app/proguard-rules.pro
- android/app/src/main/java/org/getlantern/mobilesdk/model/SessionManager.kt
- android/app/src/main/java/org/getlantern/mobilesdk/util/DnsDetector.java
- android/app/src/main/kotlin/org/getlantern/lantern/MainActivity.kt
- android/app/src/main/kotlin/org/getlantern/lantern/event/EventBus.kt
- android/app/src/main/kotlin/org/getlantern/lantern/event/EventManager.kt
- android/app/src/main/kotlin/org/getlantern/lantern/model/LanternSessionManager.kt
- android/app/src/main/kotlin/org/getlantern/lantern/notification/NotificationReceiver.kt
- android/app/src/main/kotlin/org/getlantern/lantern/service/LanternService.kt
- pubspec.lock
- pubspec.yaml
Resolves https://github.com/getlantern/engineering/issues/1453
This is needed to complete the Flutter upgrade to 3.22.2
> Remove use of org.greenrobot.eventbus and implement event bus using shared flow

- .github/workflows/prerelease-notification.yml
- .github/workflows/release-changelog.yml
- .github/workflows/release.yml
> Enable CI workflow.

- README.md
* libayatana-appindicator (required by tray_manager)
* gstreamer (required by flutter plugin audioplayers)
* libclang-dev (required by ffigen)
> [docs] Add dependency for Linux

- android/app/src/main/kotlin/org/getlantern/lantern/model/ProviderInfo.kt
- lib/plans/checkout.dart
- lib/plans/utils.dart
Waiting on an update to return a HTTPS redirect URL then I'll finish testing this
> Add support for Shepherd payment provider

- lib/plans/plan_details.dart
Fix for the following crash on desktop:
```
flutter: [2024-07-25 12:03:09.277149 | Catcher 2 | INFO] ---------- ERROR ----------
flutter: [2024-07-25 12:03:09.277174 | Catcher 2 | INFO] LateInitializationError: Field 'methodChannel' has not been initialized.
flutter: [2024-07-25 12:03:09.277197 | Catcher 2 | INFO]
flutter: [2024-07-25 12:03:09.277318 | Catcher 2 | INFO] ------- STACK TRACE -------
flutter: [2024-07-25 12:03:09.277430 | Catcher 2 | INFO] #0      Model.methodChannel (package:lantern/common/model.dart)
flutter: [2024-07-25 12:03:09.277454 | Catcher 2 | INFO] #1      SessionModel.isGooglePlayServiceAvailable (package:lantern/common/session_model.dart:855:26)
flutter: [2024-07-25 12:03:09.277475 | Catcher 2 | INFO] #2      _PlanCardState._processCheckOut …
```
> Only call isGooglePlayServiceAvailable if isPlayVersion is true

- android/app/src/main/kotlin/io/lantern/model/SessionModel.kt
- android/app/src/main/kotlin/org/getlantern/lantern/model/InAppBilling.kt
- android/app/src/main/kotlin/org/getlantern/lantern/model/LanternSessionManager.kt
Added support for 1 Month plans for Google in-app purchase
> Update product IDS

- ios/Podfile.lock
- lib/catcher_setup.dart
- lib/main.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- Added sentry for new flutter desktop version
- Update sentry setup
> Update Sentry setup 

- lib/ffi.dart
- lib/home.dart
- lib/plans/checkout.dart
- lib/plans/checkout_legacy.dart
- lib/plans/plan_details.dart
- lib/plans/utils.dart
Resolves https://github.com/getlantern/engineering/issues/1545
> Open shepherd payment provider in system browser

- android/app/build.gradle
- android/app/src/main/kotlin/io/lantern/model/MessagingModel.kt
- android/app/src/main/kotlin/io/lantern/model/ReplicaModel.kt
- android/app/src/main/kotlin/io/lantern/model/SessionModel.kt
- android/app/src/main/kotlin/io/lantern/model/dbadapter/DBAdapter.kt
- android/app/src/main/kotlin/org/getlantern/lantern/MainActivity.kt
- lib/features/home/session_model.dart
This PR fixes the below issues
> - Google Play Top crash related to crash while on transaction
The only way I can produce it is, I to run it multiple times and I will get that crash once in a while, I made some changes on android-db, Which might fix the issue, 
> Another issue with Error while commit
That is also fixed with this.
> Crash Rate fixes

- android/app/src/main/kotlin/org/getlantern/lantern/service/LanternService.kt
10-14 19:07:40.742 23405 23405 E AndroidRuntime: java.lang.RuntimeException: Unable to create service org.getlantern.lantern.service.LanternService: kotlin.UninitializedPropertyAccessException: lateinit property session has not been initialized
10-14 19:07:40.742 23405 23405 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4925)
10-14 19:07:40.742 23405 23405 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
10-14 19:07:40.742 23405 23405 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
10-14 19:07:40.742 23405 23405 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-14 19:07:40.742 23405 23405 E AndroidRuntime: 	at …
> Fix lateinit property session has not been initialized

- README.md
- lib/app.dart
Meant to remove this from the changes to the system icon
> Remove darkTheme setting

- lib/features/vpn/vpn_notifier.dart
This PR fixes an issue with UI being now shown after the flashlight takes longer to fetch config.
> Fix Desktop Init

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR fixes the issue of not uploading the debug symbol to Google Play.
> Upload debug symbol and 

- .github/workflows/build.yml
- .github/workflows/release.yml
Android CI is failing due to low disk space, This update Android CI to use new runner.
> Update android runner to use high config runner.

- .github/workflows/go.yml
solves https://github.com/getlantern/engineering/issues/1781
> update soon-to-be deprecated upload-artifact@v4

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR fixes issue with Android build is not uploading to play store
> Fix Android CI

- internalsdk/session_model.go
- ios/Runner/Lantern/Models/SessionModel.swift
- lib/core/service/app_purchase.dart
- lib/core/service/injection_container.dart
- lib/features/checkout/plan_details.dart
- lib/main.dart
This PR fixes top two crash of iOS.
- One with feature enable on Go side
- Other one with in app purchase module.
> 8.0.4 Crash fixes

- .github/workflows/prerelease-notification.yml
This PR updates the pre-release workflow to use platform-specific tags and also sends slack messages only if CI is successfully run
> Update Pre-release workflow.

- .github/workflows/prerelease-notification.yml
- .github/workflows/release.yml
- Fix the issue with failing test flight step
- Support pushing out platform-specific versions such as android, ios , desktop
> Release CI Fixes.

- android/app/src/main/AndroidManifest.xml
- internalsdk/session_model.go
- lib/features/home/session_model.dart
This PR removes media permission.  According to Google, we need to remove it. unless the core- feature of the app is photo and video others have to migrate to system-picker
> Remove MEDIA permisson.

- .github/workflows/go.yml
- Makefile
- README.md
Some improvements to Makefile and README while testing replica update builds on Android and MacOS.
> Build tidy

- Makefile
- android/app/build.gradle
- android/app/src/main/kotlin/org/getlantern/lantern/model/MessagingHolder.kt
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/gradlew
- android/gradlew.bat
- android/settings.gradle
- ios/Podfile.lock
- lib/common/ui/custom/text.dart
- lib/features/account/settings.dart
- lib/features/messaging/notifications.dart
- lib/features/replica/logic/uploader.dart
- lib/features/replica/ui/utils.dart
- lib/features/replica/upload/review.dart
- lib/features/replica/upload/title.dart
- pubspec.lock
- pubspec.yaml
This PR replaces the [flutter_uploader](https://pub.dev/packages/flutter_uploader) package with [background_downloader](https://pub.dev/packages/background_downloader).
Android CI is failing because flutter_uploader is outdated and references PluginRegistry.Registrar https://github.com/getlantern/lantern-client/actions/runs/13292622151/job/37116867601 It hasn't been maintained, making it incompatible with the latest Flutter
```
/home/runner/.pub-cache/hosted/pub.dev/flutter_uploader-3.0.0-beta.4/android/src/main/java/com/bluechilli/flutteruploader/FlutterUploaderPlugin.java:18: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
> Task :flutter_uploader:compilePlayJavaWithJavac FAILED
^
symbol:   class Registrar
location: interface PluginRegistry …
```
> Replace flutter_uploader with background_downloader

- desktop/app/app.go
- desktop/lib.go
- internalsdk/pro/pro.go
- internalsdk/pro/user.go
- internalsdk/session_model.go
- lib/core/service/lantern_ffi_service.dart
- lib/core/service/websocket_subscriber.dart
- lib/features/device_linking/authorize_device_via_email.dart
- lib/features/device_linking/authorize_device_via_email_pin.dart
- lib/features/home/session_model.dart
- lib/generated_bindings.dart
- macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Resolves https://github.com/getlantern/engineering/issues/1991
> Fix issues linking device via email on desktop

- assets/locales/en-us.po
- lib/features/auth/sign_in.dart
- lib/features/checkout/store_checkout.dart
- lib/main.dart
- macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Added some UI changes for App store changes.
> App store review changes.

- internalsdk/ios/ios.go
This pull request refactors the `iosClient` implementation in `internalsdk/ios/ios.go` to improve modularity and simplify the handling of dialers and trackers. Key changes include moving dialer initialization and configuration logic into dedicated methods, consolidating tracker updates, and removing redundant code.
* **Dialer Initialization and Configuration:**
- Introduced a new `reconfigure` method in `iosClient` to handle dialer reconfiguration, consolidating logic previously spread across multiple methods.
- Added a new `onDialers` method to encapsulate the dialer options setup, improving code readability and maintainability.
* **Tracker Integration:**
- Moved tracker initialization into the `iosClient` struct and removed redundant local tracker variables in methods like `start`. …
> Clean up handling of new dialers on iOS

- desktop/lib.go
- internalsdk/session_model.go
- lib/core/service/lantern_ffi_service.dart
- lib/features/account/report_issue.dart
- lib/features/home/session_model.dart
- lib/generated_bindings.dart
- linux/CMakeLists.txt
closes https://github.com/getlantern/engineering/issues/2130
This commit adds functionality to collect and share diagnostic logs across desktop and mobile platforms. It introduces a new "Share logs" button (except on Linux) that bundles log files into a ZIP archive and allows sharing them.
> Add function to collect and share logs

- .github/workflows/build.yml
- Makefile
- android/build.gradle
Resolves https://github.com/getlantern/engineering/issues/2153
> Downgrade minSdkVersion to 21

- go.mod
- go.sum
This primarily addresses this bug that resulted from poor idempotency handling in kindling:
https://github.com/getlantern/engineering/issues/2262
> Update to kindling that has better idempotency handling

- desktop/app/app.go
- desktop/app/pro.go
- desktop/lib.go
- go.mod
- go.sum
- internalsdk/pro/pro.go
- internalsdk/session_model.go
- internalsdk/webclient/webclient.go
- lib/features/checkout/reseller_checkout_legacy.dart
- lib/generated_bindings.dart
This pull request introduces enhanced logging, user state updates, and minor improvements to API request handling. The changes primarily focus on improving debugging capabilities, ensuring proper user state management, and refining the behavior of API interactions.
* Added detailed debug logs to track user-related operations such as fetching/creating users, refreshing user data, and cache lookups in `desktop/app/app.go` and `desktop/app/pro.go`. This includes logs for user ID and language settings. [[1]](diffhunk://#diff-1d93015a39a8bfe4942fdefaa1473038b5323d8191e9151cf38f503c826e2bbbR539-R552) [[2]](diffhunk://#diff-1d63c69ef41fd6c652c5e22c30a9122753c7f7d1c87798dca558aba4e03493b8R71-R77)
* Updated user state by setting the `ProUser` status during user data fetch and reseller code …
> Fix reseller code issue
