getlantern/lantern-client

.github/workflows/release.yml
Using `s3-actions/s3cmd` breaks CI:
```
Run s3-actions/s3cmd@v1.4.0
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
If you wish to install a non-brew-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
If you wish to install a non-brew packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
```  
https://github.com/getlantern/lantern-client/actions/runs/8612860713/job/23602954471#step:20:1
This updates the release workflow to install s3cmd with pip …
=> Remove use of s3-actions, use pip to install s3cmd

android/app/src/main/kotlin/org/getlantern/lantern/util/ApkInstaller.kt
04-11 14:25:50.214 26834 26935 E ApkInstaller: Failed to install apk
04-11 14:25:50.214 26834 26935 E ApkInstaller: java.lang.IllegalArgumentException: org.getlantern.lantern: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
=> Use FLAG_IMMUTABLE creating PendingIntent in ApkInstaller

desktop/lib.go, lib/common/session_model.dart, lib/ffi.dart, lib/plans/checkout.dart, lib/vpn/protos_shared/vpn.pb.dart, lib/vpn/protos_shared/vpn.pbjson.dart, protos_shared/vpn.proto
- Update ffiPaymentRedirect to use compute
- Add PaymentRedirect API response type
- Update email exists check to return string instead of pointer
This also fixes an issue on main with desktop where the following error is shown after opening the payment redirect page
=> Update ffiPaymentRedirect to use compute

lib/common/ui/app_webview.dart, lib/plans/checkout.dart, lib/plans/utils.dart
We only want to open the redirect URL returned by `/payment-redirect` in the system browser on macOS iff the payment provider is Fropay
=> Only open Fropay in system browser on macOS

desktop/app/issue.go, desktop/app/pro.go, desktop/lib.go, lib/account/account.dart, lib/common/session_model.dart, lib/ffi.dart, lib/plans/checkout.dart, lib/plans/utils.dart
In the old Pro client, whenever we fetch user data, it is stored afterwards in a local cache. Whenever that cache changes, the updates are sent over the websocket channel: https://github.com/getlantern/flashlight/blob/main/pro/user_data.go#L154
It looks this was left out of the [new Pro client](https://github.com/getlantern/lantern-client/pull/1033), and we were no longer receiving user data updates in real-time: https://github.com/getlantern/lantern-client/blob/7163452b617d7a7384d2f050bfbf80cde38db3fb/lib/common/session_model.dart#L94
=> Fix issue updating user data over websocket

desktop/lib.go, lib/account/device_linking/authorize_device_via_email.dart, lib/account/report_issue.dart, lib/common/common.dart, lib/common/ui/custom/text_field.dart, lib/ffi.dart, lib/home.dart, lib/plans/checkout.dart
Resolves https://github.com/getlantern/engineering/issues/1336
- Make text fields 56px high on desktop
- Remove floating label near cursor from text area on report issue screen
=> Lantern Desktop Beta 8.0.0 collected testing issues

lib/common/common.dart, lib/i18n/i18n.dart, pubspec.lock, pubspec.yaml
Some changes to handle upgrading intl to 0.19.0 and i18n_extension to 12.0.1
```
➜  lantern-client git:(atavism/7.8.6) ✗ flutter pub get
Resolving dependencies...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.
Because lantern depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because lantern depends on intl ^0.18.0, version solving failed.
```
```
➜  lantern-client git:(atavism/7.8.6) ✗ flutter build macos
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-000809843A08201E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008112-000809843A08201E, name:My Mac } …
```
=> Update how i18n imports translations

.github/workflows/build-windows.yml
For flutter-version-file to work on Windows, yq has to be installed first
https://github.com/mikefarah/yq
=> install yq prior to building desktop app on Windows

go.mod, go.sum
=> updating flashlight version

internalsdk/pro/pro.go, internalsdk/pro/webclient/defaultwebclient/rest.go
This PR updates defaultwebclient to use a different type of request middleware where RawRequest is not nil.
go-resty has "three types of request middleware, and they are performed in sequence:
- udBeforeRequest chain (registered by Client.onBeforeRequest)
- beforeRequest chain (default middleware registered by resty)
- preReqHook hook (registered by Client.SetPreRequestHook)
RawRequest is initialized at the second chain. Therefore, we get nil in our onBeforeRequest function."
=> Update pro client request middleware

android/app/src/main/AndroidManifest.xml
The latest build submitted to the Play store was rejected because they found "that [our] app is not compliant with how the USE_FULL_SCREEN_INTENT permission is allowed to be used. Specifically, the use of the permission is not directly related to the core purpose of the app ... Apps will only be automatically granted to use the USE_FULL_SCREEN_INTENT permission if the core functionality of their app falls under one of the below categories that require high priority notifications: setting an alarm or receiving phone or video calls"
=> Remove use of USE_FULL_SCREEN_INTENT permission

lib/account/settings.dart
Resolves https://github.com/getlantern/engineering/issues/1499
Opens the privacy policy and terms of service pages in the system browser on mobile instead of an in app webview (which is currently displaying a blank page)
=> Open privacy policy and terms of service in browser on mobile

hit_proxy.bash
ptool has been subsumed by `lantern-cloud/bin/lc`. This PR updates hit_proxy.bash to use it instead.
=> Update hit_proxy script to use bin/lc

android/app/src/main/kotlin/org/getlantern/lantern/model/PaymentMethod.kt
Resolves the following issue:
```
08-21 18:51:58.859 17375 17608 E JsonUtil: Unable to parse JSON
08-21 18:51:58.859 17375 17608 E JsonUtil: kotlinx.serialization.MissingFieldException: Field 'paymentwall' is required for type with serial name 'org.getlantern.lantern.model.Icons', but it was missing at path: $
08-21 18:51:58.859 17375 17608 E JsonUtil: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:95)
08-21 18:51:58.859 17375 17608 E JsonUtil: 	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:165)
08-21 18:51:58.859 17375 17608 E JsonUtil: 	at org.getlantern.lantern.model.LanternHttpClient$plansV4$1.onSuccess(SourceFile:147)
08-21 18:51:58.859 17375 17608 E JsonUtil: 	at …
```
=> Specify default values for provider icons

ios/Podfile.lock, macos/Podfile.lock, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Fixes two new issues building the macOS app:
```
/Users/paul/.pub-cache/hosted/pub.dev/flutter_inappwebview_macos-1.0.11/macos/Classes/InAppWebView/InAppWebView.swift:870:26: error: method does not override any method from its superclass
public override func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)? = nil) {
^
open func evaluateJavaScript(_ javaScriptString: String, completionHandler: (@MainActor @Sendable (Any?, (any Error)?) -> Void)? = nil)
^
/Users/paul/.pub-cache/hosted/pub.dev/flutter_inappwebview_macos-1.0.11/macos/Classes/InAppWebView/InAppWebView.swift:10:1: warning: add '@preconcurrency' to suppress 'Sendable'-related warnings from module 'WebKit'
import WebKit
^
```
And
```
Error: CocoaPods's specs repository is too out-of-date …
```
=> Fix macOS build error: method does not override any method from its superclass

lib/home.dart
We weren't checking that auth is enabled when we redirect first time users to the auth landing page
=> Only check first time visit if auth is enabled

lib/vpn/vpn_switch.dart, macos/Podfile.lock
For https://github.com/getlantern/engineering/issues/1652
```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
setState() or markNeedsBuild() called during build.
This VPNSwitch widget cannot be marked as needing to build because the framework is already in the
process of building widgets. A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this widget during this build phase.
The widget on which …
```
=> delay call to setState with addPostFrameCallback

lib/features/vpn/vpn_bandwidth.dart
Fix for the following issue: "When first installed, I saw a data cap, but when I did a clean install on another Windows user account, I saw no data cap. After about 10 minutes of use, the data cap showed up again."
This is happening because we only display the data cap once we receive a bandwidth update for the first time. We should update the code to do that if the feature is enabled instead but for now I'm just always enabling it on desktop to fix the immediate issue.
=> Always show data cap on desktop

go.mod, go.sum
This pull request is updating the reference to the latest audoupdate version that validates the response code from the downloaded version is different than 200. We're doing this so we can try to understand better why the `autoupdate_download` operation is failing. See https://github.com/getlantern/autoupdate/pull/11 for more details
=> updating autoupdate and run go mod tidy

lib/app.dart, lib/features/home/home.dart, lib/features/window/window_container.dart, lib/main.dart
This PR includes updates to wrap the app in a window container. This encapsulates window management in a separate widget and makes it easier to maintain.
=> Add Window container

lib/app.dart, lib/features/home/home.dart, lib/features/tray/tray_container.dart
This PR introduces a TrayContainer, similar to the recent changes to add a WindowContainer, and updates LanternApp to conditionally wrap both containers only on desktop.
It removes direct usage of tray_manager from the home widget, which was previously responsible for initializing the tray.
=> Implement TrayContainer and refactor LanternApp to use it

go.mod, go.sum, hit_proxy.bash
This PR updates the config filename and wraps the `dump-config` output with the keys flashlight expects. There might be a better way to handle this instead of hard-coding it.
=> Update hit_proxy scipt to work with new config format.

desktop/app/app.go, desktop/lib.go, desktop/settings/settings.go, internalsdk/android.go, internalsdk/pro/user.go, internalsdk/session_model.go
This PR fixes the issue while calling user-create API on Android multiple times, Also sometimes `/plans` get called before the user creates still on going so other API calls fail because due user is not found.
=> Fix user create api on android.

Makefile, desktop/app/app.go, internalsdk/ios/ios.go, ios/Tunnel/BandwidthTracker.swift
This pr added support back for the stats tracker for iOS and fixed issues with bandwidth.
=> iOS updates with new flashlight

.github/workflows/build.yml, .github/workflows/release.yml, Makefile, android/app/build.gradle
This PR adds support for uploading debug symbols to the Play Store, which will help us deobfuscate logs.
=> Upload debug symbols

go.mod, go.sum, internalsdk/ios/config.go, internalsdk/ios/geolookup/geolookup.go, internalsdk/ios/geolookup/geolookup_test.go
Since iOS uses it's own code to fetch proxy configs instead of the grouped request, it's unable to retrieve geolocation. This PR adds the old geolookup code exclusively for iOS to use. 
The `geolookup` package was copied directly from flashlight's old [geolookup package](https://github.com/getlantern/flashlight/blob/ebfaa2b5ed6208689f296d20312d5924c7bd3476/geolookup/geolookup.go).
=> use previous geolookup for ios

desktop/lib.go, go.mod, go.sum, internalsdk/issue.go
This PR depends on https://github.com/getlantern/flashlight/pull/1471
=> Report issue Fix

android/app/build.gradle, android/app/proguard-rules.pro, android/app/src/main/AndroidManifest.xml
This PR includes fixes for the issue from Leviathan.
Here is the ticket-: https://github.com/getlantern/engineering/issues/1741
=> Security assessment fixes

.github/workflows/release.yml
I'm unable to push a new 8.0.0 release because of the following issue uploading the iOS build to Testflight: https://github.com/getlantern/lantern-client/actions/runs/12958781057/job/36150481991#step:11:16
> This bundle is invalid. The value for key CFBundleShortVersionString [8.0.0] in the Info.plist file must contain a higher version than that of the previously approved version [8.0.5]
I'm not sure how we fix this @jigar-f? I'm just going to disable uploading the iOS build to Testflight for now to get a release out. FYI @Derekf5
=> Disable uploading build to Testflight for now

ios/Podfile.lock, ios/Runner/Info.plist
```
In Podfile:
sentry_flutter (from `.symlinks/plugins/sentry_flutter/ios`) was resolved to 8.13.0, which depends on
Sentry/HybridSDK (= 8.44.0)
You have either:
* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
* changed the constraints of dependency `Sentry/HybridSDK` inside your development pod `sentry_flutter`.
You should run `pod update Sentry/HybridSDK` to apply changes you've made
```
=> Fix some iOS build issues in CI

.github/workflows/build.yml, .github/workflows/release.yml, pubspec.lock
This updates CI to copy the Windows installer to the correct location as lantern-installer.exe, removing the unnecessary x64 extension (which I think comes from lantern-desktop)
=> Fix incorrect Windows installer name in production CI

.github/workflows/build.yml
I meant to revert this change before merging https://github.com/getlantern/lantern-client/pull/1332
=> use macos-15 runner instead of latest

.github/workflows/build.yml
Resolves https://github.com/getlantern/engineering/issues/2154
The Windows runner wasn’t correctly propagating the VERSION env var to the Makefile due to some shell inconsistencies. This updates the CI step to explicitly pass VERSION=${{ env.VERSION }} to make
Tested here https://github.com/getlantern/lantern-client/actions/runs/15099221080/job/42437969802#step:27:29
=> Fix version override issue on Windows

hit_proxy_v2.bash
This pull request introduces a new script, `hit_proxy_v2.bash`, designed to dynamically fetch and configure proxies for the Lantern client based on user-defined criteria. The script includes robust argument parsing, validation, and error handling, as well as support for caching and dynamic proxy selection. Below are the key features and changes:
- **Dynamic proxy fetching and configuration**:
- Allows fetching proxy configurations based on `track`, `protocol`, or `provider` criteria.
- Supports direct proxy IP input, bypassing dynamic selection.
- Implements caching for proxy lists with options to force refresh or use cached results.
- Randomly selects a valid proxy from fetched lists when multiple options are available.
- **Enhanced usability**:
- Provides detailed usage instructions and …
=> add new hit_proxy_v2.bash script
